
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale} from 'next-intl/server';
import {LocationProvider} from '../app/context/LocationContext'
import {LikeProvider} from '../app/context/LikedContext'
import {AdminProvider} from '../app/context/TchebaaAdminContext'
import {UserProvider} from '../app/context/UserContext'
import {DateProvider} from '../app/context/DateContext'
import {Amplify} from 'aws-amplify'
import { generateClient } from 'aws-amplify/data';
import {type Schema} from '../../tchebaa-backend/amplify/data/resource'
import outputs from '../../amplify_outputs.json'






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  


  const handleGetLocale = async () => {

    const locale = await getLocale()

    console.log(locale)

  }


  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <UserProvider>
            <LikeProvider>
              <LocationProvider>
                <AdminProvider>
                  <DateProvider>
                    {children}
                  </DateProvider>
                </AdminProvider>
              </LocationProvider>
            </LikeProvider>
          </UserProvider>
        </NextIntlClientProvider>
        
       
      </body>
    </html>
  );
}
